import React from 'react';
import { Link } from 'react-router-dom';
import { Mail, Phone, MapPin, Globe, Cpu, Shield, Upload, FileText, CheckCircle } from 'lucide-react';
import Footer from '../components/Footer';
import { motion } from 'framer-motion';

function Landing() {
  const fadeInUp = {
    initial: { opacity: 0, y: 20 },
    whileInView: { opacity: 1, y: 0 },
    viewport: { once: true },
    transition: { duration: 0.6 }
  };

  const staggerContainer = {
    initial: { opacity: 0 },
    whileInView: { opacity: 1 },
    viewport: { once: true },
    transition: { staggerChildren: 0.1 }
  };

  return (
    <div>
      <div className="container">
        <motion.nav 
          className="navbar"
          initial={{ opacity: 0, y: -20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.5 }}
        >
          <div className="logo">PlagCheck</div>
          <div className="nav-links">
            <a href="#features" style={{ color: 'var(--text-dim)', textDecoration: 'none', marginLeft: '2rem', fontWeight: 500 }}>Features</a>
            <a href="#how-it-works" style={{ color: 'var(--text-dim)', textDecoration: 'none', marginLeft: '2rem', fontWeight: 500 }}>How It Works</a>
            <a href="#about" style={{ color: 'var(--text-dim)', textDecoration: 'none', marginLeft: '2rem', fontWeight: 500 }}>About Us</a>
            <Link to="/contact" style={{ color: 'var(--text-dim)', textDecoration: 'none', marginLeft: '2rem', fontWeight: 500 }}>Contact</Link>
            <Link to="/login" style={{ marginLeft: '2rem' }}>Log In</Link>
            <Link to="/register">
              <button>Get Started</button>
            </Link>
          </div>
        </motion.nav>
        
        <section className="hero">
          <motion.h1 
            initial={{ opacity: 0, scale: 0.9 }}
            animate={{ opacity: 1, scale: 1 }}
            transition={{ duration: 0.8 }}
          >
            Ensure your work is <span className="text-gradient">original.</span>
          </motion.h1>
          <motion.p 
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            transition={{ delay: 0.3, duration: 0.8 }}
          >
            Scan your documents and source code against our massive intelligence engine to detect overlaps and protect your intellectual property.
          </motion.p>
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.6, duration: 0.5 }}
          >
            <Link to="/register">
              <button style={{ padding: '1.2rem 3rem', fontSize: '1.1rem' }}>Start Scanning</button>
            </Link>
          </motion.div>
        </section>

        <section id="features" style={{ padding: '8rem 0' }}>
          <motion.div 
            style={{ textAlign: 'center', marginBottom: '4rem' }}
            {...fadeInUp}
          >
            <h2 style={{ fontSize: '3rem', fontWeight: 800, marginBottom: '1.5rem' }}>Powerful <span className="text-gradient">Features.</span></h2>
            <p style={{ color: 'var(--text-dim)', fontSize: '1.15rem', maxWidth: '700px', margin: '0 auto' }}>Equipped with state-of-the-art tools to maintain the highest standards of originality.</p>
          </motion.div>

          <motion.div 
            style={{ display: 'grid', gridTemplateColumns: 'repeat(3, 2fr)', gap: '2rem' }}
            variants={staggerContainer}
            initial="initial"
            whileInView="whileInView"
            viewport={{ once: true }}
          >
            {[
              { icon: Cpu, title: "Code Analysis", text: "Specialized engine to detect plagiarism in source code, scripts, and programming assignments." },
              { icon: Shield, title: "AI Detection", text: "Instantly identify if the content was generated by AI models like ChatGPT, Claude, or Gemini." },
              { icon: FileText, title: "Detailed Reports", text: "Get a comprehensive breakdown of similarity scores and specific overlapping segments." },
              { icon: Upload, title: "Multi-Format Upload", text: "Seamlessly upload PDF, TXT, and various code files or simply paste your text directly." },
              { icon: Globe, title: "Global Database", text: "Comparison against a massive dataset of academic papers, web content, and public repositories." },
              { icon: CheckCircle, title: "Instant Results", text: "Our high-performance TF-IDF engine delivers analysis results in just seconds." }
            ].map((feature, index) => (
              <motion.div 
                key={index}
                className="card"
                variants={fadeInUp}
                whileHover={{ y: -10, boxShadow: '0 20px 40px rgba(0,0,0,0.08)' }}
              >
                <div style={{ background: 'rgba(245, 158, 11, 0.1)', width: '50px', height: '50px', borderRadius: '12px', display: 'flex', alignItems: 'center', justifyContent: 'center', marginBottom: '1.5rem' }}>
                  <feature.icon size={24} color="var(--primary)" />
                </div>
                <h3 style={{ marginBottom: '1rem' }}>{feature.title}</h3>
                <p style={{ color: 'var(--text-dim)' }}>{feature.text}</p>
              </motion.div>
            ))}
          </motion.div>
        </section>

        <section id="how-it-works" style={{ padding: '8rem 0' }}>
          <motion.div 
            style={{ textAlign: 'center', marginBottom: '4rem' }}
            {...fadeInUp}
          >
            <h2 style={{ fontSize: '3rem', fontWeight: 800, marginBottom: '1.5rem' }}>How it <span className="text-gradient">Works.</span></h2>
            <p style={{ color: 'var(--text-dim)', fontSize: '1.15rem', maxWidth: '700px', margin: '0 auto' }}>Our platform uses advanced mathematical algorithms to ensure the integrity of your work in three simple steps.</p>
          </motion.div>
          
          <motion.div 
            style={{ display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: '2rem' }}
            variants={staggerContainer}
            initial="initial"
            whileInView="whileInView"
            viewport={{ once: true }}
          >
            {[
              { id: "01.", title: "Content Upload", text: "Paste your text or upload your source code files directly into our secure scanner." },
              { id: "02.", title: "Deep Analysis", text: "Our TF-IDF engine compares your content against millions of data points in our global dataset." },
              { id: "03.", title: "Detailed Result", text: "Receive an instant similarity score and a detailed breakdown of overlapping segments." }
            ].map((step, index) => (
              <motion.div 
                key={index}
                className="card"
                variants={fadeInUp}
                whileHover={{ scale: 1.02 }}
              >
                <h3 style={{ color: 'var(--primary)', marginBottom: '1rem' }}>{step.id} {step.title}</h3>
                <p style={{ color: 'var(--text-dim)' }}>{step.text}</p>
              </motion.div>
            ))}
          </motion.div>
        </section>

        <section id="about" style={{ padding: '8rem 0' }}>
          <motion.div 
            style={{ textAlign: 'center', marginBottom: '4rem' }}
            {...fadeInUp}
          >
            <h2 style={{ fontSize: '3rem', fontWeight: 800, marginBottom: '1.5rem' }}>About <span className="text-gradient">Us.</span></h2>
            <p style={{ color: 'var(--text-dim)', fontSize: '1.15rem', maxWidth: '700px', margin: '0 auto' }}>We are dedicated to maintaining the global standards of academic and professional integrity through innovative technology.</p>
          </motion.div>

          <motion.div 
            className="card" 
            style={{ maxWidth: '900px', margin: '0 auto', lineHeight: '1.8' }}
            initial={{ opacity: 0, x: -50 }}
            whileInView={{ opacity: 1, x: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.8 }}
          >
            <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '3rem' }}>
              <div>
                <h3 style={{ marginBottom: '1.5rem', color: 'var(--dark-bg)' }}>Our Mission</h3>
                <p style={{ color: 'var(--text-dim)' }}>
                  PlagCheck was founded with a single goal: to provide everyone with access to reliable, fast, and accurate originality validation. Whether you are a student submitting a thesis or a developer protecting your source code, we believe that integrity should be accessible to all.
                </p>
              </div>
              <div>
                <h3 style={{ marginBottom: '1.5rem', color: 'var(--dark-bg)' }}>Our Technology</h3>
                <p style={{ color: 'var(--text-dim)' }}>
                  By leveraging the latest in Natural Language Processing and similarity detection algorithms, we provide a robust intelligence engine that understands context, structure, and intent, moving beyond simple keyword matching.
                </p>
              </div>
            </div>
          </motion.div>
        </section>
      </div>

      <Footer />
    </div>
  );
}

export default Landing;
